### PR TITLE
upgrade to postgres 11

### PR DESCRIPTION
**Pull request by pega-roska**
Postgres 9.4 has less than a year left of support.  It would be good to update this to something more modern.

### CODE REVIEW

**Comment by cdancy** [comment]
@pega-roska while these changes look OK the resulting image size 500+ MB's in size (current images are about 160 MB's). By removing all of the "clean" code each layer is keeping all of that data unnecessarily. We would have to either put those back in or have single "run" task which would use 1 layer that we could easily clean up.

**Comment by cdancy** [comment]
Scratch the above comment as it looks like things are in a single layer ... maybe it's the removal of the "apt clean" calls? Or maybe 9.11 is just that much bigger than 9.4? IDK. Something fishy is up here...

**Comment by pega-roska** [comment]
So, the existing 9.4 image shows as 469MB in `docker image ls` when I pull it, so I have no idea where Docker Hub is getting it's numbers from.

Regardless, I did notice while analysing the new image that we were leaving behind the pljava src dir, which we really didn't need, so I was able to shave ~20MB from the new image, bringing it down to 492MB, as reported by `docker image ls`.  That's still a little larger than the original, but at this point all of the extra size is coming from the upstream postgres image.

**Comment by cdancy** [comment]
Taking this in. Thanks for the PR @pega-roska !

**Comment by cdancy** [comment]
Branch `9.11` has been created with these changes (changes are also available on master) and new `9.11` image pushed.

**Comment by cdancy** [comment]
Correction: Branch `11` has been created with corresponding image `11` pushed to dockerhub.

**Pull request merged**
